title:             개발 일지
email:             jihwan2534@gmail.com
description:       Jihwan Developer Daily
author:            Jihwan
baseurl:           ""
url:               "https://JihwangGo.github.io"

# Social Profiles
twitter_username:  ""
github_username:   "jihwango"
facebook_username: "https://www.facebook.com/profile.php?id=100003556601725"

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
